version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/identity-provider"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/mcp-client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
